-- 운송 변경 이력 테이블
CREATE TABLE TCAR_TRANSPORT_HIST (
    HIST_ID       NUMBER         PRIMARY KEY,
    TRANSPORT_ID  NUMBER         NOT NULL,
    ACTION        VARCHAR2(10)   NOT NULL,
    ROW_LABEL     VARCHAR2(500),
    DETAIL        VARCHAR2(4000),
    CHANGED_BY    VARCHAR2(100),
    CHANGED_AT    DATE           DEFAULT SYSDATE
);
CREATE SEQUENCE TCAR_TRANSPORT_HIST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_TCAR_TRANSPORT_HIST_AT ON TCAR_TRANSPORT_HIST (CHANGED_AT DESC);
