-- TCAR_TRANSPORT 추가 항목 (상차폰/사업자, 사진/지급, 입금, 계산서발행, 내역서, 비고)
ALTER TABLE TCAR_TRANSPORT ADD (
    LOADING_PHONE   VARCHAR2(200),
    PHOTO_PAYMENT   VARCHAR2(200),
    DEPOSIT         VARCHAR2(200),
    INVOICE_ISSUED  VARCHAR2(200),
    STATEMENT_DOC   VARCHAR2(200),
    REMARK          VARCHAR2(1000)
);
COMMIT;
