-- 웹 푸시 알림: 구독 정보 / 앱 설정(VAPID 키) / 로그인 알림 수신자 플래그
CREATE TABLE TCAR_PUSH_SUB (
    SUB_ID      NUMBER          PRIMARY KEY,
    KAKAO_ID    VARCHAR2(50)    NOT NULL,
    ENDPOINT    VARCHAR2(1000)  NOT NULL,
    P256DH      VARCHAR2(200)   NOT NULL,
    AUTH        VARCHAR2(100)   NOT NULL,
    USER_AGENT  VARCHAR2(300),
    CREATED_AT  DATE            DEFAULT SYSDATE
);
CREATE UNIQUE INDEX UX_TCAR_PUSH_SUB_ENDPOINT ON TCAR_PUSH_SUB (ENDPOINT);
CREATE SEQUENCE TCAR_PUSH_SUB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- VAPID 키 등은 코드/저장소가 아니라 DB에 보관 (최초 사용 시 자동 생성)
CREATE TABLE TCAR_APP_CONFIG (
    CFG_KEY     VARCHAR2(50)    PRIMARY KEY,
    CFG_VALUE   VARCHAR2(2000)
);

-- 로그인 알림을 받을 사용자 (Y 인 사용자의 기기로 푸시 발송)
ALTER TABLE TCAR_USER_KAKAO ADD NOTIFY_LOGIN VARCHAR2(1) DEFAULT 'N' NOT NULL;
-- 예: UPDATE TCAR_USER_KAKAO SET NOTIFY_LOGIN = 'Y' WHERE NICKNAME LIKE '%전태환%';
COMMIT;

-- 푸시 발송 이력 (기기 1대 발송 = 1건). 한글 컬럼은 CHAR 단위 길이로 지정
CREATE TABLE TCAR_PUSH_LOG (
    LOG_ID           NUMBER             PRIMARY KEY,
    SENT_AT          DATE               DEFAULT SYSDATE NOT NULL,
    TYPE             VARCHAR2(10)       NOT NULL,
    TARGET_KAKAO_ID  VARCHAR2(50),
    SUB_ID           NUMBER,
    ACTOR_KAKAO_ID   VARCHAR2(50),
    ACTOR_NAME       VARCHAR2(100 CHAR),
    TITLE            VARCHAR2(200 CHAR),
    BODY             VARCHAR2(500 CHAR),
    RESULT           VARCHAR2(10)       NOT NULL,
    HTTP_CODE        NUMBER(4),
    ERROR_MSG        VARCHAR2(500 CHAR)
);
CREATE SEQUENCE TCAR_PUSH_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_TCAR_PUSH_LOG_AT ON TCAR_PUSH_LOG (SENT_AT);
