-- 운송 데이터 소유자 (TCAR_USER_KAKAO.IS_ADMIN 'Y'/'N' 은 기존 컬럼 사용)
ALTER TABLE TCAR_TRANSPORT ADD CREATED_BY VARCHAR2(50);   -- 작성자 KAKAO_ID (NULL = 관리자만 조회)
-- 관리자 지정 예: UPDATE TCAR_USER_KAKAO SET IS_ADMIN = 'Y' WHERE NICKNAME LIKE '%전태환%';
COMMIT;
