-- 캘린더(D-day/생일) 테이블 및 푸시 구독 앱 구분 컬럼
CREATE TABLE TCAL_ITEM (
    ITEM_ID          NUMBER              PRIMARY KEY,
    OWNER_KAKAO_ID   VARCHAR2(50)        NOT NULL,
    ITEM_TYPE        VARCHAR2(10)        NOT NULL,
    TITLE            VARCHAR2(100 CHAR)  NOT NULL,
    BASE_DATE        DATE                NOT NULL,
    HAS_YEAR         NUMBER(1)           DEFAULT 1 NOT NULL,
    COUNT_FROM_ONE   NUMBER(1)           DEFAULT 1 NOT NULL,
    INTERVAL_DAYS    NUMBER(5)           DEFAULT 100 NOT NULL,
    YEARLY           NUMBER(1)           DEFAULT 1 NOT NULL,
    NOTIFY_DAYS      VARCHAR2(50)        DEFAULT '7,1,0',
    MEMO             VARCHAR2(500 CHAR),
    IS_HIDDEN        NUMBER(1)           DEFAULT 0 NOT NULL,
    CREATED_AT       DATE                DEFAULT SYSDATE
);
CREATE SEQUENCE TCAL_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_TCAL_ITEM_OWNER ON TCAL_ITEM (OWNER_KAKAO_ID);
CREATE TABLE TCAL_NOTIFY_LOG (
    ITEM_ID      NUMBER      NOT NULL,
    OCCUR_DATE   DATE        NOT NULL,
    DAYS_BEFORE  NUMBER(3)   NOT NULL,
    SENT_AT      DATE        DEFAULT SYSDATE,
    CONSTRAINT PK_TCAL_NOTIFY_LOG PRIMARY KEY (ITEM_ID, OCCUR_DATE, DAYS_BEFORE)
);
ALTER TABLE TCAR_PUSH_SUB ADD APP VARCHAR2(20) DEFAULT 'TRANSPORT' NOT NULL;
