-- ============================================================
-- CAR_TRANSPORT → TCAR_TRANSPORT 마이그레이션 + 장표 파일 테이블 생성
-- Oracle SQLPlus 에서 실행
-- ============================================================

-- 1. TCAR_TRANSPORT 테이블 생성
CREATE TABLE TCAR_TRANSPORT (
    ID               NUMBER          PRIMARY KEY,
    TRANSPORT_DATE   DATE            NOT NULL,
    DRIVER_NAME      VARCHAR2(100),
    COMPANY          VARCHAR2(100),
    LOADING_POINT    VARCHAR2(200),
    UNLOADING_POINT  VARCHAR2(200),
    CAR_MODEL        VARCHAR2(100),
    VEHICLE_NO       VARCHAR2(50),
    SUPPLY_PRICE     NUMBER(15)      DEFAULT 0,
    COMPANY_PRICE    NUMBER(15)      DEFAULT 0,
    CREATED_AT       DATE            DEFAULT SYSDATE
);

-- 2. TCAR_TRANSPORT 시퀀스 생성
CREATE SEQUENCE TCAR_TRANSPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 3. 기존 데이터 이관 (CAR_TRANSPORT 테이블이 있는 경우)
-- INSERT INTO TCAR_TRANSPORT
-- SELECT ID, TRANSPORT_DATE, DRIVER_NAME, COMPANY,
--        LOADING_POINT, UNLOADING_POINT, CAR_MODEL, VEHICLE_NO,
--        SUPPLY_PRICE, COMPANY_PRICE, CREATED_AT
-- FROM CAR_TRANSPORT;
-- COMMIT;

-- 4. 이관 후 시퀀스 값 조정 (기존 데이터가 있는 경우)
-- DECLARE
--     v_max NUMBER;
-- BEGIN
--     SELECT NVL(MAX(ID), 0) + 1 INTO v_max FROM TCAR_TRANSPORT;
--     EXECUTE IMMEDIATE 'DROP SEQUENCE TCAR_TRANSPORT_SEQ';
--     EXECUTE IMMEDIATE 'CREATE SEQUENCE TCAR_TRANSPORT_SEQ START WITH ' || v_max || ' INCREMENT BY 1 NOCACHE';
-- END;
-- /

-- 5. TCAR_TRANSPORT_FILE 테이블 생성 (장표 첨부파일)
CREATE TABLE TCAR_TRANSPORT_FILE (
    FILE_ID         NUMBER          PRIMARY KEY,
    TRANSPORT_ID    NUMBER          NOT NULL,
    ORIGINAL_NAME   VARCHAR2(500)   NOT NULL,
    SAVED_NAME      VARCHAR2(500)   NOT NULL,
    FILE_PATH       VARCHAR2(1000),
    FILE_SIZE       NUMBER(15)      DEFAULT 0,
    FILE_EXT        VARCHAR2(20),
    CREATED_AT      DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_TCAR_TRANSPORT_FILE
        FOREIGN KEY (TRANSPORT_ID) REFERENCES TCAR_TRANSPORT(ID)
);

-- 6. TCAR_TRANSPORT_FILE 시퀀스 생성
CREATE SEQUENCE TCAR_TRANSPORT_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 7. (선택) 구 테이블 삭제 - 이관 확인 후 직접 실행
-- DROP TABLE CAR_TRANSPORT;
-- DROP SEQUENCE CAR_TRANSPORT_SEQ;

COMMIT;
