-- ============================================================
-- TCAR 네이밍 규격 마이그레이션
-- 실행 순서대로 수행할 것
-- ============================================================

-- ① TCAR_USER_KAKAO 테이블 생성 (IS_ADMIN 컬럼 포함)
CREATE TABLE TCAR_USER_KAKAO (
    USER_SEQ         NUMBER          PRIMARY KEY,
    KAKAO_ID         VARCHAR2(50)    UNIQUE NOT NULL,
    NICKNAME         VARCHAR2(100),
    PROFILE_IMAGE    VARCHAR2(500),
    AUTO_LOGIN_TOKEN VARCHAR2(100),
    TOKEN_EXPIRE     DATE,
    LAST_LOGIN       DATE,
    IS_ADMIN         VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    INSERT_DATE      DATE            DEFAULT SYSDATE
);

CREATE SEQUENCE TCAR_USER_KAKAO_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE;

-- ② TUSER_KAKAO → TCAR_USER_KAKAO 데이터 이관
INSERT INTO TCAR_USER_KAKAO (
    USER_SEQ, KAKAO_ID, NICKNAME, PROFILE_IMAGE,
    AUTO_LOGIN_TOKEN, TOKEN_EXPIRE, LAST_LOGIN, INSERT_DATE
)
SELECT
    USER_SEQ, KAKAO_ID, NICKNAME, PROFILE_IMAGE,
    AUTO_LOGIN_TOKEN, TOKEN_EXPIRE, LAST_LOGIN, INSERT_DATE
FROM TUSER_KAKAO;

-- 시퀀스를 기존 최댓값 이후부터 시작하도록 조정
-- (이관한 데이터가 있을 경우 충돌 방지)
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(USER_SEQ), 0) + 1 INTO v_max FROM TCAR_USER_KAKAO;
    EXECUTE IMMEDIATE 'DROP SEQUENCE TCAR_USER_KAKAO_SEQ';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TCAR_USER_KAKAO_SEQ START WITH ' || v_max || ' INCREMENT BY 1 NOCACHE';
END;
/

COMMIT;

-- ③ TCAR_MAINTENANCE 테이블 생성
CREATE TABLE TCAR_MAINTENANCE (
    ID               NUMBER          PRIMARY KEY,
    KAKAO_ID         VARCHAR2(50)    NOT NULL,
    KAKAO_NICKNAME   VARCHAR2(100),
    CAR_NAME         VARCHAR2(100),
    CAR_NUMBER       VARCHAR2(20),
    MAINTENANCE_DATE DATE,
    MILEAGE          NUMBER(10),
    MAINTENANCE_TYPE VARCHAR2(50),
    DESCRIPTION      VARCHAR2(2000),
    COST             NUMBER(15),
    SHOP_NAME        VARCHAR2(200),
    CREATED_AT       DATE            DEFAULT SYSDATE,
    UPDATED_AT       DATE
);

CREATE SEQUENCE TCAR_MAINTENANCE_SEQ
    START WITH 1 INCREMENT BY 1 NOCACHE;

-- ④ CAR_MAINTENANCE → TCAR_MAINTENANCE 데이터 이관 (데이터가 있는 경우)
INSERT INTO TCAR_MAINTENANCE
SELECT * FROM CAR_MAINTENANCE;

DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max FROM TCAR_MAINTENANCE;
    EXECUTE IMMEDIATE 'DROP SEQUENCE TCAR_MAINTENANCE_SEQ';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TCAR_MAINTENANCE_SEQ START WITH ' || v_max || ' INCREMENT BY 1 NOCACHE';
END;
/

COMMIT;

-- ============================================================
-- 기존 테이블 삭제 (이관 확인 후 실행)
-- ============================================================
-- DROP TABLE TUSER_KAKAO;
-- DROP SEQUENCE TUSER_KAKAO_SEQ;
-- DROP TABLE CAR_MAINTENANCE;
-- DROP SEQUENCE CAR_MAINTENANCE_SEQ;
